### ISSUE TITLE
Contradiction about Machine mode accessibility to dmode accessibility

### ISSUE THREAD

**Issue by gokhankaplayan** [riscv-non-isa/riscv-external-debug-security#24]
https://github.com/riscv-non-isa/riscv-external-debug-security/blob/8b547b57459b957e5d5a99993d1110422a3953e2/chapter2.adoc?plain=1#L99
> The extension relaxes the constrain to the dmode, allowing it to be R/W in machine mode when mdbgen is set to 0. When mdbgen is set to 0, it remains exclusively accessible within Debug Mode.

The above two sentences are contradicting. The second sentence should be updated with the following: When mdbgen is set to **1**, it remains exclusively accessible within Debug Mode.

**Comment by AoteJin** [comment]
Right, thanks for catching it! Will update.
