### ISSUE TITLE
sec_check in VS/U-mode is not defined?

### ISSUE THREAD

**Issue by zhangdujiao** [riscv-non-isa/riscv-external-debug-security#34]
Table 3. the sec_check is specified only in M-mode and S/HS-mode. 
Why is the sec_check signals in VS and U modes not specified?

**Comment by AoteJin** [comment]
The table 3 defines the sec_check signal value regarding the configuration of machine mode and sub-machine mode knob. The sub-machine mode knob controls the behavior of S/HS, U, VS, VU modes, thus all modes are covered in the table.

**Comment by AoteJin** [comment]
I suppose there is no open question, closing
